openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of the contact app
tags:
  - name: Contacts
    description: Operation with contacts
servers:
  - url: http://127.0.0.1:3000  # ЯК В ЛЕКЦІЇ 29:01
  - url: https://your-deployed-site.com  # ТРЕБА ВПИСАТИ ВИРНИЙ САИТ
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    patch: 
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
  /contacts:
    get: 
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: 32329f

